### PR TITLE
Preload webfonts to improve loading speed

### PR DESCRIPTION
**Pull request by theasteve**
remove any flash of unstyled text (FOUT)
*related: https://web.dev/codelab-preload-web-fonts/

Screen Shot 2020-09-30 at 12 29 25 PM

Preloaded fonts based on the lighthouse report

### CODE REVIEW

**Review by devowhippit — CHANGES_REQUESTED** [review]
@theasteve keep in mind multilingual fonts and only preload for specific families.

https://github.com/CityOfNewYork/ACCESS-NYC-PATTERNS/blob/main/src/elements/fonts/_fonts.scss

**Review by theasteve — COMMENTED** [review]
@theasteve  Based on this post it make sense to change preload to prefetch https://github.com/GoogleChromeLabs/preload-webpack-plugin/issues/8

**Review by devowhippit — CHANGES_REQUESTED** [review]
@theasteve the approach I would like you to take is to prefetch/preload fonts based on the language code of the site. [This file can also tell you what fonts are used based on the language code](https://github.com/CityOfNewYork/ACCESS-NYC-PATTERNS/blob/main/src/elements/fonts/_fonts.scss).

[The language code is set to the global context by the site controller](https://github.com/CityOfNewYork/ACCESS-NYC/blob/4fb13f93622c8cf7d7beb4df9558c02239d5f497/wp-content/themes/access/controllers/site.php#L39) so when you see `$context = Timber::get_context();` it is available in the map @ `$context['language_code']`.

Also, the [wp_resource_hints](https://developer.wordpress.org/reference/functions/wp_resource_hints/#source) filter supports `preload` in addition to `prefetch`. Based on our learnings from the #259 this can be done programmatically in our view controllers.

**Review by devowhippit — CHANGES_REQUESTED** [review]
It seems better from an organizational perspective to move this into `controllers/site.php` since it is the same on every view.

**Review by devowhippit — APPROVED** [review]

**Review by theasteve — COMMENTED** [review]
Looks Good!

**Pull request merged**
